service: myserverlessproject
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: myseverlessprojectuploadbucket-123123
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
# you can add CloudFormation resource templates here
resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myseverlessprojectuploadbucket-123123
